### ISSUE TITLE
Wrong website in readme

### ISSUE THREAD

**Issue by rcastellotti** [eciavatta/caronte#26]
I think you messed up something while adding ur website in the readme, maybe u meant [eciavatta.DEV?](https://eciavatta.it)
![image](https://user-images.githubusercontent.com/43064224/118395175-326ffd00-b649-11eb-9d3d-d83a4488cdcf.png)

**Comment by eciavatta** [comment]
Yes, my personal website is eciavatta.dev. Thanks for letting me know, I just fixed it! :)

**Comment by rcastellotti** [comment]
;) np
