### ISSUE TITLE
Packets which match the flag regex won't highlight

### ISSUE THREAD

**Issue by kriive** [eciavatta/caronte#50]
First things first: thanks for the wonderful project!

Reading your README.md I saw that one of the features mentions the highlight of the packets matching the regex, but in my experience this doesn't happen.

For example:
![image](https://user-images.githubusercontent.com/24835026/130447239-55575140-5cec-4875-b4c7-77917cb4dba3.png)

I tried it with Firefox and Chrome on Linux. Is caronte supposed to highlight the flags or did I get it wrong?

**Comment by eciavatta** [comment]
I just released a hotfix that fixes the problem introduced in the last release. It should now correctly highlight the rules.\
You should pull the new image with `docker-compose pull` to see the changes.

Thanks for reporting it!

![image](https://user-images.githubusercontent.com/4194510/130518253-ec4e59f4-cb9b-4ec4-a9d4-fab29a24f536.png)
